### ISSUE TITLE
2D Animator and Designer looking for interesting topics to animate!

### ISSUE THREAD

**Issue by wm-ad** [leios/SoME_Topics#106]
Hi! My name's William.

## Portfolio

WEBSITE
www.wmad.co.uk

WORK FOR TOM SCOTT
https://www.wmad.co.uk/#/tom-scott/

WORK FOR MATT PARKER
https://www.wmad.co.uk/#/matt-parker/

WORK FOR ROYAL INSTITUTION
https://www.wmad.co.uk/#/secretsandlies/
https://www.wmad.co.uk/#/who-am-i/

## Target topic categories

Maths, computer science, physics, linguistics – but open to anything interesting!

## Target medium

I'd be available to create 2D animated videos in an explainer video style, a green screen presenter style, or even an abstract visual style. I'd also be able to design 2D static assets such as branding, advertising, and infographics.

### Contact details

EMAIL
wm@wmad.co.uk

### Additional context

I've worked a lot with sci-comm YouTubers such as Tom Scott, Matt Parker, and Steve Mould amounting a total of over 70 million views.

**Comment by aargup934** [comment]
My idea is at #18. I hope to cover topics such as graph theory, Ramsey theory, Pigeonhole principle and other basic combinatorial topics with some olympiad problems.

**Comment by ChristianLange96** [comment]
Hi William. I'm super impressed with your work! I'd love to collaborate with you on a video on error correction on a quantum computer. It's not a scary as it sounds ;-) I think some nice 2D animations can be made to make it easier to understand and more accessible. Check out my idea at #71 if you're interested.

**Comment by rudrathegreat** [comment]
Hello Hello! My name is Rudra Sekhri and I'm a high school student from Australia! My video idea is called "Ducks, Dragons and Composite Functions!", feel free to read more from this issue #138. I would really appreciate it if we could collaborate! Love all the work you have done!

**Comment by wm-ad** [comment]
Hi there, thanks for reaching out!

This sounds great, feel free to email me at ***@***.*** ***@***.***> with more details of your idea (including budget).

Thanks,

Will

**Comment by wm-ad** [comment]
Hi there, thanks for reaching out!

This sounds great, feel free to email me at ***@***.*** ***@***.***> with more details of your idea (including budget).

Thanks,

Will

**Comment by wm-ad** [comment]
Hi there, thanks for reaching out!

This sounds great, feel free to email me at ***@***.*** ***@***.***> with more details of your idea (including budget).

Thanks,

Will

**Comment by wm-ad** [comment]
Hi there, thanks for reaching out!

This sounds great, feel free to email me at ***@***.*** ***@***.***> with more details of your idea (including budget).

Thanks,

Will

**Comment by wm-ad** [comment]
Sorry all, thanks to a private email from Calvin above, I now better understand the purpose of this forum. I mistakenly used it to advertise myself for freelance projects and now am aware that's not appropriate. As wonderful as all your projects sound, I'm not available for free collaborations at this time. Sorry for wasting your time and best of luck with your projects!

**Comment by leios** [comment]
For the record, as long as you are clear about offering paid services, it is technically fine to submit work to SoME2. The way we see it, people pay others for animations all the time. If SoME2 allows people to create a more "professional" collaboration, that is fine.

The fear is that SoME2 becomes "pay to win," but right now I don't see that happening.

**Comment by cmh231** [comment]
Indeed! Apologies, the intention wasn't to say that only free partnerships were allowed here - I've seen at least one other person offering paid work - just that it seems to be assumed unless stated otherwise!
