### ISSUE TITLE
Simulating electric fields and ions with the finite difference method

### ISSUE THREAD

**Issue by igmanthony** [leios/SoME_Topics#107]
## About the author

I'm an assistant professor at Maastricht University in the Netherlands working in the field of chemical instrumentation (mostly imaging mass spectrometers). I am bad at math.

## Quick Summary

The first atomic bomb was made by [purifying uranium](https://en.wikipedia.org/wiki/Calutron#:~:text=A%20calutron%20is%20a%20mass,his%20earlier%20invention%2C%20the%20cyclotron.) - one charged atom (ion) at a time - by controlling where each uranium ion flew. Today, we have precision instruments that can guide ions more precisely and accurately. The first step of building these instruments is to simulate electric and magnetic fields. Using these fields we then simulate the ions' flight paths. To do these simulations, we use numerical methods (the finite difference method) to solve [Laplace's equation](https://en.wikipedia.org/wiki/Laplace%27s_equation#Electrostatics_2) for the electric fields and then "roll" the ions down the "hill" to see where they end up.

The idea would be to show how the finite difference method works to simulate electric fields. Then the video would make the connection of how we use math to simulate ions just like we do if we wanted to simulate the physics of golf balls on a hill. I'd love to get into ideas of how we can extract more insights and information than we put in. For example, very simple simulations can provide solutions to rather complex problems and show a lot of beauty with concepts such as resonance and frequencies.

## Target medium

A 3B1B video-style format with animations/voiceover would be my idea for the content, although I am open to other ideas. I would hope the length would be as short as possible (maybe at most 20 minutes, ideally shorter).

### More details

I have an interactive website that I am working on [here](https://igmanthony.com/fields-ions-optics/) to help teach students. Below is an image that was generated interactively of an ion's path (the black line) that was "unstable" and escaped the trap (the surface).
![download](https://user-images.githubusercontent.com/17777713/173105825-d3f04628-ec8e-4c82-b94d-c88cd6b49b70.png)
So I have working [code](https://github.com/igmanthony/fields-ions-optics)/examples (in Python, Rust, Javascript, and even Microsoft Excel) that could be used to make animations or help out. I think they could look really nice, but I don't have video editing skills. You can see some other examples of simulations in the website.

The purpose of the website is ultimately more about what we simulate, but the start discusses some of the concepts involved in the simulations themselves.

I can provide more details if you're interested but I'd also be open to hearing if you have any ideas.

### Contact details

You can contact me here or at igmanthony@gmail.com

**Comment by reduccionista** [comment]
Can you describe that graphic with equations? i guess yes, or maybe they are experimental data. Because if you can, those surfaces can be animated in Manim

**Comment by igmanthony** [comment]
Thanks for the question! I didn't want to go too long/write too much, but yes! The "surface" was generated from the "electrodes" that are the darkest blue and darkest red (and flat green) surfaces. The way that the height map that is the surface was generated was by using the finite difference method to "diffuse" out the electric fields from the electrodes, kind of like stretching a rubber sheet.

The black squiggly line is the trajectory of an ion that was "flown". It moves back and forth because the surface is actually moving all around (because the electrode values are changing with time to trap the ion). The surface can absolutely be animated, as can the particle trajectory. 

The "data" in this case are all simulation-based. In the [https://igmanthony.com/fields-ions-optics/laplace_equation.html](website) I linked I have a maybe better explanation of how this is done. Please let me know if you have any other questions or if you have an interest in trying something out!
