### ISSUE TITLE
The n=3 case of Fermat's Last Theorem

### ISSUE THREAD

**Issue by rp2knight** [leios/SoME_Topics#117]
## About the author

I'm Emma Knight, a number theorist who is about to move into finance.  I also enjoy problem solving, and you can see my solutions to 538's riddler at https://emma-knight.ca/riddlers/

## Quick Summary

The topic I'm interested in is to give a proof of the n=3 case of Fermat's Last Theorem, i.e. that there are no integers x, y, and z such that x^3 + y^3 = z^3 and xyz =/= 0.  This proof touches on a lot of subjects that are not too technical but slip through the cracks of a lot of elementary number theory exposition.

## Target medium

I'm interested in many ways to make this into a presentation.  A video would probably take more work from the producer as I am almost completely new to creating video content.  If you are interested in making a website or a blog post, then I am more able to help out.

If you have a novel idea for how to present this, I'm all ears.

### More details

This will err on the more advanced side of things: I am likely assuming that the audience has some familiarity with some standard number theory results (unique prime factorization, modular arithmetic) as well as some basics of the complex numbers.

There probably will need to be two parts: one talking about the Eisenstein integers and one going into the proof of the theorem itself.  I do not know of a straightforward and not too technical way to present this material without talking a bit about the Eisenstein integers in detail.

Tentative idea of what needs to be done:
I) Eisenstein integers (Z[\zeta_3])
a) Definition, visualization, norm
b) Main theorems: classification of units and unique factorization
c) Modular arithmetic in the Eisenstein integers, focusing on the example of Z[\zeta_3]/((1-\zeta_3)^k) for a couple of small values of k
II) The proof of Fermat's Last Theorem
a) The induction gambit: instead of proving x^3 + y^3 = z^3 has no nontrivial solutions for x, y, and z rational integers, we will instead show the equation x^3 + y^3 = u(1-\zeta_3)^nz^3 where x, y, and z are Eisenstein integers coprime to 1-\zeta_3, u is a unit, and n is an integer that is congruent to either 0 or 2 mod 3
b) The first half of the actual proof: show that, if there is a solution to the modified equation above, then n >= 4
c) The second half of the actual proof: show that, if you have a solution to the above equation with n >= 5, then you can find a solution for n-3

### Contact details

I can be contacted through this thread here, or through email (me@emma-knight.ca).

### Additional context

The proof that I know of is basically the proof that is in Hardy and Wright.  In some sense, this will be an exposition on a section in that book, but I think that there is real appeal in presenting this to a wider audience.

**Comment by Sir-Mastermind** [comment]
Could you provide the proof? It would be good to know what the proof is before talking about feasibility.

**Comment by rp2knight** [comment]
Good call; that's been added!

**Comment by neondata** [comment]
could you take a look here: https://cmapspublic3.ihmc.us:443/rid=1Y6K63YZG-1TL6BN4-3MB/Why_are_there_pythagorean_triples.cmap and tell me you opinion?
