### ISSUE TITLE
Mobile app for highly interactive try-it-yourself topics

### ISSUE THREAD

**Issue by Lootwig** [leios/SoME_Topics#128]
I am an app developer (mind you, not designer) and have built multiple corporate projects as a freelancer.
These are usually data-entry focused though, and I'd love to build something with more of a playful/educational content just as a fun side project.

## Portfolio

I have worked for STIHL, Peek&Cloppenburg, the Luminate Group, e.on and an insurance company.

## Target topic categories

A prime example of what a mobile experience can add to topics presentation-wise is kurzgesagt's [Universe in a Nutshell ](https://www.google.com/url?sa=t&source=web&rct=j&url=https://shop-us.kurzgesagt.org/products/universe-in-a-nutshell-app&ved=2ahUKEwjkg6WE-qX4AhXLO-wKHZxIBKwQFnoECAoQAQ&usg=AOvVaw11gT_pyN8Hx03drHd9W6p3) app. Anything that is fun to observe when tweaking parameters and possible to compute realtime on the device, or can be pre-rendered.

## Target medium

Mobile (iOS and Android) as well as web app.

### Contact details

Just describe or link to your idea in here!

**Comment by ComboClass** [comment]
Hi! My name's Dimitri. I've been interesting in building up an educational website (or possible apps in the future) in conjunction with the more chaotically structured math videos I've been releasing. I would love to hire someone (although I don't have a huge budget yet) to help design online interfaces for several ideas of mine, such as:
- ways of rearranging blocks representing integers to test/guess which ones would be prime numbers or square numbers or other patterns. similarly, showing geometric things like how the number 1 under a square number can be factored into a nearly-square rectangular shapes.
- ways of rearranging sequences like odd numbers, triangular numbers, square numbers, cube numbers, and sums of those, to show the many interconnected patterns between them
- clicking through slowly-divergent reciprocal functions, and guessing whether they will ever converge or diverge
- interacting with graphed functions where you can drag/change parameters, along the lines of the interactive Newton's Method graphics on the 3Blue1Brown website, but related to other functions
- interactive versions of some classic logic puzzles from the past that require a clever "aha" moment of logical deduction to solve
- ... and several other ideas of mine which I only know the mathematical (not programming) aspects of, but have ideas of ways they could form the basis of interactive games/puzzles/interfaces

If interested in discussing any possibilities, feel free to email me at [combouniversity@gmail.com](combouniversity@gmail.com)

**Comment by gabrielfougeron** [comment]
Dear David,

I've written a set of python scripts to find periodic solutions to the N-body gravitationnal problem, which I describe briefly in #23 .
I am currently trying to write a webapp version of it, but I struggle since I'm no webdevelopper. This is actually my fist time ever tinkering with HTML, CSS, Javascript etc ...

I'd be grateful if you would take some time to consider my project, and tell me if you find it inspiring. Maybe we could devise a game out of it ?

Regards,

Gabriel

**Comment by Lootwig** [comment]
Hey @gabrielfougeron , thanks for reaching out!
I wouldn't mind brainstorming over whether there's a nice way to build something interactive out of your idea, or the math behind it - what's a good way to get in touch?

**Comment by gabrielfougeron** [comment]
Awesome!
Are you in GMT+2 ? We could schedule a zoom call one night this week if you want.

**Comment by Lootwig** [comment]
I am. How's Thursday 9pm?

**Comment by Lootwig** [comment]
Oh no, that slipped past me I'm so sorry!
Can offer either later tonight (not at home right now) or anytime tomorrow?

Again, sorry for messing this up!
Kind regards,
David

**Comment by gabrielfougeron** [comment]
Hey,

No worries :-D

I’m in vacation stating tommorow, for a whole week. Anytime tonight before midnight is fine with me.

Best,

Gabriel



De : ***@***.***>
Envoyé le :jeudi 16 juin 2022 21:14
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [leios/SoME_Topics] Mobile app for highly interactive try-it-yourself topics (Issue #128)

Oh no, that slipped past me I'm so sorry!
Can offer either later tonight (not at home right now) or anytime tomorrow?

Again, sorry for messing this up!
Kind regards,
David

**Comment by Lootwig** [comment]
Let's do eleven thirty then - I assume the link you sent is still good then?

**Comment by gabrielfougeron** [comment]
Great !

I assume so too. If not, I’ll make another one 😊



De : ***@***.***>
Envoyé le :jeudi 16 juin 2022 22:00
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [leios/SoME_Topics] Mobile app for highly interactive try-it-yourself topics (Issue #128)

Let's do eleven thirty then - I assume the link you sent is still good then?
