### ISSUE TITLE
Ducks, Dragons and Composite Functions! By a High School Student

### ISSUE THREAD

**Issue by rudrathegreat** [leios/SoME_Topics#138]
## About the author

Hello Hello! My name is Rudra Sekhri and I'm a high school student from Australia currently studying mathematics, physics, chemistry and more!

For more information about me, visit my LinkedIn below  -
https://www.linkedin.com/in/rudra-sekhri-02162219b/

## Quick Summary

As you can tell by the title, the idea of this video will be about trying to explain the essence of composite functions using ducks and duck-eating dragons! The video will first go over what a function is and representing that with ducks. Then, it will explain what composite functions are by presenting the idea of a duck (one function) inside a dragon (another function) and understanding some of the properties of composite functions before learning how to compute them and finishing them off with some worked examples.

## Target medium

- Video
- Use of manim animations for the math in the video
- Use of illustrations for explanation-parts of the video
- Targeted towards high-school students

### Contact details

Feel free to reply to the post and I'll be more than happy to provide further contact details

### Additional context

Where did this idea come from? When I sat in my classroom to first learn about composite functions, I and many other found it a very annoying topic. After my teacher showed me this way to visualise the idea of composite functions, things fell in place so easily and it made so much logical sense. I want other people to know about this ingenious method to understanding the essence of composite functions!

**Comment by Ghostly726** [comment]
Hi there,
after reading about your idea, i would really like to attempt to animate it using manim

**Comment by rudrathegreat** [comment]
thanks so much! is it ok if you could share some of your existing work in manim @Ghostly726 ???

**Comment by Ghostly726** [comment]
https://user-images.githubusercontent.com/107476091/173735127-ae1189de-1b71-468b-8046-d698fabba170.mp4

I made this video a little while back, and im inishing up more as we speak

**Comment by rudrathegreat** [comment]
wow! fantastic work!!! this looks awesome! I think we got ourselves a collab! My email is rudrasekhri@gmail.com! Feel free to contact me directly through there!

**Comment by rudrathegreat** [comment]
that last animation with the zooming in was really cool! it would be cool if we used that in transitions and other cool stuff! In terms of dates. I should have some script done in 2 weeks time (e.g. 30th June) and then from there, we can come up with a storyboard together to fit the whole video and then create a first draft of the video

**Comment by Ghostly726** [comment]
Marvellous! ill startworking soon and hopefully provide updates in a timely manner

**Comment by rudrathegreat** [comment]
thanks! appreciate it! feel free to provide ur email address so that we can get started!

**Comment by Ghostly726** [comment]
abdulrahmankhaledal32021@gmail.com

**Comment by rudrathegreat** [comment]
hi @Ghostly726, just wanted to let you know that I'm currently getting feedback for the script and updating it. I will send it to you once I've implemented all the feedback. Once I send you the script, we can work together to quickly create a storyboard, and from there, get started in animating the video. Also got permission from Vince Rubinetti to use the same music 3blue1brown uses in his videos

**Comment by rudrathegreat** [comment]
feel free to keep sending your awesome animations as you complete them!

**Comment by Ghostly726** [comment]
Hi there!
so as a way to start explaining composite functions, i think we should start by explaining what are functions, so I visualized what functions are in 2 ways, graphically and algebraically
in the graphical part, I'm yet to include labels, but it includes normal, polar, and 3D surface functions

https://user-images.githubusercontent.com/107476091/174478314-8193c61c-651e-4be3-b0e2-940e33cffa1b.mp4


https://user-images.githubusercontent.com/107476091/174478316-cf25b35e-b695-4ff0-bffb-16ef57f1c158.mp4

**Comment by Ghostly726** [comment]
its worth to note that I'm yet to use actual ducks and dragons (which are really nice to animate ill share a video about that soon), but I have a idea.
There is another way to visualize composite functions using algorithms! where the output of f(x) is the input of g(f(x)), ill share a video soon, but tell me if that's something you like to be shown

**Comment by Ghostly726** [comment]
oh and currently I'm improving the algebra part

**Comment by rudrathegreat** [comment]
love the work! i think it's best if we first get the script ready before doing any animations. Otherwise, you would be wasting your time and creating animations that wouldn't be in the final video. I like the the algebraic one. I think with the graphing one, it would be great if you could slow down the animations slightly while the graph is appearing. That would be awesome! Don't worry! I think I'll be able to animate the part with the ducks and the dragons!

**Comment by rudrathegreat** [comment]
it's pretty much done, just getting the final rounds of feedback. Then what I'll do is split up the script into "manim animations" and non-manim animations. You can animate the manim parts because I suck at manim, and then I can create the non-manim animations, because it will help add movement to the story (look at 3blue1brown's latest video for an example of different animating styles),

**Comment by Ghostly726** [comment]
ducks and dragons animation on manim is kinda clean, but i like the idea of diff animation styles. Ill be waiting for your script

**Comment by Ghostly726** [comment]
oh and for the music i prefer "trinkets" for any math intensive parts of a video

**Comment by rudrathegreat** [comment]
same here! i love "trinkets", but I think this video isn't going to be too heavy on math. Remember, this is intended of high school students (somewhere my age). I think multiple tracks in the video would be awesome! don't worry! I'll edit the video!

**Comment by Ghostly726** [comment]
very well! On whose channel wll the vid be uploaded? Just for keeping i the back of mind

**Comment by rudrathegreat** [comment]
most likely on my youtube channel. I already have content on it, and it's all about science and math.

**Comment by Ghostly726** [comment]
marvelous! make sure to submit it on the SoME 2 form, so we enter the competition!

**Comment by rudrathegreat** [comment]
yep!

**Comment by Ghostly726** [comment]
alright! expect some updated animations shortly

**Comment by rudrathegreat** [comment]
thanks! although as I mentioned before, animations are not required just yet until I've sent you the script. Otherwise, you won't know what to animate! Feel free to get a break. Don't worry! I should have it sent to you this coming Wednesday to your email

**Comment by Ghostly726** [comment]
oh ok, as you wish!

**Comment by rudrathegreat** [comment]
appreciate it man! if you want to make animations, feel free to! Just keep in the back of ur mind that it's just practice, and most of those animations won't make it in the final. just something to improve, would really appreciate it if you could slow down the graph animations slightly

**Comment by Ghostly726** [comment]
https://user-images.githubusercontent.com/107476091/174492243-b6f6d1f1-a2b2-49b9-84ab-944bba57cd69.mp4

**Comment by Ghostly726** [comment]
animations are a bit slower

**Comment by rudrathegreat** [comment]
that looks really good!
