### ISSUE TITLE
Game Dev/Houdini Artist Looking to Create Beautiful Visualizations

### ISSUE THREAD

**Issue by tomgiagtz** [leios/SoME_Topics#14]
## Intro

First, just some background on me. I'm a web developer, turned game development student. I'm fascinated by code-driven art, and about a year ago, Houdini became my procedural paintbrush. I want to help you paint an intuition for some mathematical wonder. 

## Portfolio

https://www.artstation.com/tomgia
And check out my [GitHub](https://github.com/tomgiagtz)!

## Target topic categories

I have a soft spot for vector math, learning everything used in 3D programs has been my joy over the last couple of months.
But, I'm aware that my scope is rather limited from that, so anything that can be represented nicely in 3D would be a great topic. If your topic involves more than 3 dimensions, then I can't wait to help try and find an intuitive way to represent it. 

## Target medium

I'd like to create a 3D animation, and produce a video from it. I'm also well versed in Unity: want to make a game? I'm all ears!

### Contact details

Discord:[ tee o emm#7685](https://discordapp.com/users/tee%20o%20emm#7685)
Email: tjg86@drexel.edu

### Additional context

I think I got it all above 😄 

(Any additional licensing information? If you do not say anything, this post will be considered [CC-BY](https://creativecommons.org/licenses/by/2.0/).)

**Comment by PatrickGambill** [comment]
Hi! A couple of my possible projects ideas involve making games. I detailed them on my post here https://github.com/leios/SoME_Topics/issues/10 . If you think any of these would lead to an interesting Unity game, I would love to discuss further!

**Comment by WolfgangTheDrug** [comment]
Hey hey, I like your animation style ^^ I have a topic that you might really like - iterations and flows. I think this is a perfectly animatable topic and it would interest you as it touches ideas around iterations - your daily bread. I also know something about programming, especially webdev so can't wait for your response ^^

**Comment by JGoodrichBNL** [comment]
See my post https://github.com/leios/SoME_Topics/issues/130 and let me know if you're interested!
