### ISSUE TITLE
How the Two Big Questions of Calculus are Intertwined- A Novel Visualization

### ISSUE THREAD

**Issue by Bobtiv** [leios/SoME_Topics#147]
## About the author
I'm a high school math teacher with 20+ years in education. I teach AP Calculus among other subjects. I have a Masters in Mathematics for Educators.

## Quick Summary

How do we find the slope of a tangent line at a point on a function? What is the area under a curve on a given interval? Derivatives and integrals are the concepts used to answer each question respectively. They seem completely unrelated at first, but they are so closely related that we use the name "fundamental theorem of calculus" to describe their connection. Developing an intuitive understanding of how they are related is challenging for beginning calculus students. It's also a challenge for instructors who are faced with the task of conveying the beauty of its discovery and the deep implications for calculus suggested by its name. The goal of this project is to help the beginner calculus student develop a deeper intuitive understanding of the main ideas behind FTC, and appreciate the beautiful and surprising connections between differentiation and integration.

## Target medium

I want to produce a podcast-style video where I explore these questions to develop with my students using an interactive Desmos program. Through conversation and guided exercises we will uncover the essence of the Fundamental Theorem.

### More details

The main visualization can be seen in the the following Desmos link, but as a work in progress it may be difficult at this time for you to understand the flow of ideas that I imagine producing. In the next few days I plan to include a story-board slideshow that conveys my vision for the video and companion program. Stylistically, I'm hoping to create a conversational, podcast-like video of my students and I discussing the key ideas while using the Desmos program together. I will guide the conversation as I would in my own classroom. I hope to create something that is less scripted and more organic than the typical instructional videos seen on YouTube. The audience will learn the main ideas through the lens of students learning in a classroom setting. I am currently looking into the possibility of using our television studio here at the high school to produce high quality raw audio and video footage of these conversations.  I am looking for two kinds of expertise: 1) people who know post-production editing, and 2) an experienced Desmos programmer to create a high quality interactive Desmos activity (using Activity Builder and Desmos Computational Layer).

https://www.desmos.com/calculator/0wlqc0cvcy

### Contact details

bobtivnan@gmail.com

### Additional context

N/A

**Comment by kevinb9n** [comment]
(Just a hobbyist here.) I'm saddled with the curse that FTC seems "obvious" to me. As b increases, well, when f(b) is large the area is increasing quickly; when small, slowly; when zero, not at all, etc. The rate of change of the area is the value of the function. I think I need help relating to why this can be hard to understand for most people - and believe me, I'm not trying to insult them when I say this. What do you think the big stumbling blocks are? If you know those accurately then you'll be able to reach people where they live.

**Comment by Bobtiv** [comment]
Hi Kevinb9n, thanks for your interesting comment. I can see how it's obvious to someone that the behavior of the dA/dx "mirrors" the behavior of the function. One increases then so does the other, and likewise for decreasing behavior. From this I can understand the conjecture that dA/dx may be proportional to f(x). But lots of functions behave the same. You draw up any function and I can draw a function (infinitely many actually) that model the increasing/decreasing behavior of how the area accumulates. It's a giant a leap of faith to say that they are actually equal though. That has to be demonstrated beyond increasing and decreasing behavior. Having said this, your observation is helpful in developing an intuition about how to graph the key features of an accumulation function.

**Comment by Dayn-hues** [comment]
Very interested in this project! I am also a math teacher (just finished my 4th year) but the FTC is actually one of the few topics that has always frustrated me because I don't personally intuitively understand it. I've looked up formal proofs but I haven't really understood them honestly and more so I care more about the intuition than the rigorous proof. I get that it like doesn't not make sense (if that makes any sense haha) but I don't have an actual complete full grasp of it. While I wouldn't say I'm a pro at Desmos, I have used Desmos activities many times for my own classes and have definitely had to use the computation layer to do a lot of what I wanted so I have experience with that. I also have dabbled in video editing for fun. I am definitely a hobbyist but I have experience with both Adobe Premiere, After Effects, and Davinci Resolve. Let me know if you want to connect!

**Comment by Bobtiv** [comment]
Hi Dayn-Hues. I'm glad to hear you are interested in this project. It sounds like you have some of the computer skills that I'm looking for. Do you have any links to samples of your work with Desmos, Adobe Premiere, After Effects and Davinci Resolve? I'm particularly interested in using computational layer for Desmos Acitivity Builder. If so, please send them to me by email at bobtivnan@gmail.com. I would really be interested in working with another teacher on this so let's connect.

> Very interested in this project! I am also a math teacher (just finished my 4th year) but the FTC is actually one of the few topics that has always frustrated me because I don't personally intuitively understand it. I've looked up formal proofs but I haven't really understood them honestly and more so I care more about the intuition than the rigorous proof. I get that it like doesn't not make sense (if that makes any sense haha) but I don't have an actual complete full grasp of it. While I wouldn't say I'm a pro at Desmos, I have used Desmos activities many times for my own classes and have definitely had to use the computation layer to do a lot of what I wanted so I have experience with that. I also have dabbled in video editing for fun. I am definitely a hobbyist but I have experience with both Adobe Premiere, After Effects, and Davinci Resolve. Let me know if you want to connect!
