### ISSUE TITLE
Competition math related project

### ISSUE THREAD

**Issue by aargup934** [leios/SoME_Topics#163]
## About the author

Hi, I am Aarav Gupta, and I am currently a 14-year-old studying in high school as a freshman. I am a math enthusiast, and I am currently preparing for math olympiads. I hope to pursue a career in applied mathematics. 

## Quick Summary

I would like to create a topic highlighting some interesting problems that have come in math competitions recently. I hope to cover combinatorics mainly. I put up my original idea at #18, but since I am not able to get a collaboration in that one, I am putting up another alternative idea.

## Target medium

I hope to get the topic out there through any kind of video, illustrated article, but I hope it is something interesting, hopefully animated. I seek inspiration from last year's submission: https://youtu.be/F1Mlv-vukL0 and 3b1b's video on 2011 P2. I hope to find a content producer comfortable with Manim and other softwares

### Contact details

Please reply to this issue if you are interested.

**Comment by elancha98** [comment]
Hi,

I'm happy to see young people interested in advanced mathematics and complex topics. I do not have a lot of experience with video editting, but I have some experience with manim. I think there is some potential to talking about a complex problem specially from your perspective. I find the topics you proposed in #18 a bit too broad for my taste. I think something more concrete would be prefereable. To that end, I was thinking on some problem you found interesting, however, if you prefer to talk about some concrete concept it works out for me.

If you are interested, feel free to reply to this message (Do not feel preassured, it's fine if you don't want or prefer working with someone else :) )

**Comment by aargup934** [comment]
Will be working with @elancha98
