### ISSUE TITLE
Logic Gates in Minecraft

### ISSUE THREAD

**Issue by TvoozMagnificent** [leios/SoME_Topics#178]
## About the author

I'm a Math teacher. I'm not a professional Minecraft-er (especially in Survival), but I like Minecraft (exceptionally Creative). 

## Quick Summary

Building logic gates in Minecraft to a small computer

## Target medium

Video + Minecraft Map that includes all the stuff. (I think I don't need someone else for the Minecraft Map part.)

### More details

I have [a series of videos](https://www.youtube.com/channel/UCTp6COFrJSvqDXjhZdV-FpA) on it. 

### Contact details

Through E-mail: luchang1106@icloud.com. Or directly comment here. 

### Additional context

This post is considered [CC-BY](https://creativecommons.org/licenses/by/2.0/). 

# Target Audience

People who are interested in Minecraft. Mainly, I am going to post it on YouTube. 

# Time Available for me

My time is flexible for June and July, mainly. I usually work from 10:00 AM to 6:00 PM in Beijing Time which is 2:00 AM to 10:00 AM UTC.

**Comment by TvoozMagnificent** [comment]
# Requirements

Not much. I prefer **Manim**, but video editing or a PPT is also OK. You should at least know a little bit about Redstone in Minecraft, as in how a contraption works.

**Comment by VrutikShah** [comment]
This is quite interesting! I had once made some basic gates in Minecraft and it was fun. Good luck to you. Hope to see a working mini-computer.

**Comment by TvoozMagnificent** [comment]
By theory I could do it, but I'm not an expert on it and probably won't get everything small enough to be reasonable.

**Comment by yuhan2680** [comment]
I`m also a Minecraft redstone player and a video maker, maybe I can do it.
And you said you usually work from 10:00 AM to 6:00 PM in Beijing Time , Are you chainese? if you are, we can comunicate with Chinese.
My e-mail is 2565376223@qq.com and phone number is (+86)13544062680.

**Comment by TvoozMagnificent** [comment]
Yes I am Chinese

我现在想的是,介绍一些基本的逻辑门然后做一个3-5位的加法器 (2进制)
TRANSLATION: [What I'm now thinking is that we can introduce some simple logic gates and make a 3-5 bit (which implies base 2) full adder]

**Comment by TvoozMagnificent** [comment]
Thanks, you guys. The project is almost done!

**Comment by TvoozMagnificent** [comment]
I'm closing the issue
