### ISSUE TITLE
Basic Combinatorical ideas

### ISSUE THREAD

**Issue by aargup934** [leios/SoME_Topics#18]
## About the author

(Let people know about your current role, institution, field of expertise, or anything else that might be relevant.)
Hi, I am Aarav Gupta, and I am currently a 14-year-old studying in high school as a freshman. I am a math enthusiast, and I am currently preparing for math olympiads. I am particularly interested in the field of combinatorics, as it has a lot of applications, and some interesting questions come from it. 

## Quick Summary

(Offer a brief pitch for the lesson you'd like to create. Who is the target audience, and what are you hoping they'll get from the lesson?)
I would like to create a piece of content highlighting different combinatorical ideas such as pigeonhole principle, double counting, graph theory, and applications in computer science. 

## Target medium

(Are you hoping for your idea to be produced into a video? An illustrated/interactive article? What skillsets are you looking for in a collaborator?)
I am hoping for someone who can create a video, and is comfortable in using softwares such as manim

### More details

(If this is a topic you've written about elsewhere, e.g. in a paper or blog post, please leave a link.)

(If you have an outline or storyboard for the topic, include it here. The more detail the better.)

### Contact details

(What's the best way for people to contact you?)
My email is aargup934@gmail.com, and my discord is Aarav#9559

### Additional context

(Is there any other relevant information? Additional sources pertinent to the discussion?)

(Any additional licensing information? If you do not say anything, this post will be considered [CC-BY](https://creativecommons.org/licenses/by/2.0/).)

**Comment by TebelMeners** [comment]
I'm not a content creator
But i would like to collab with you like creating ideas
I am also preparing for math competitions

**Comment by TebelMeners** [comment]
I am not a content producer
I would like to collab with you as in creating ideas
I am also preparing for math competitions
I also would love to learn from this experience

**Comment by JGoodrichBNL** [comment]
See my post https://github.com/leios/SoME_Topics/issues/130 and let me know if you're interested!
