### ISSUE TITLE
Picturing the sphere in corners of cubes without picturing the hypersphere as a "spikey ball"

### ISSUE THREAD

**Issue by ZEKE-Foxheart** [leios/SoME_Topics#199]
## About the author

I graduated from college with a 4-year degree in math and planning to continue on into graduate school. I've been meaning to create videos on different math concepts from a less common angle.

## Quick Summary

Is there a different way to look at the hypersphere without thinking about a "spikey ball"? I will show different ways to picture a hypersphere that still fits the regular concepts of a regular sphere

## Target medium

I'm hoping to find someone who can make 3D animation to show different concepts of a hypersphere and morphing shapes to match changes in projections

### More details

The idea of looking at these concepts through projections of higher dimensional objects and animations is to connect the concepts to make a more intriguing picture and to demystify concepts of higher dimensional objects

### Contact details

You can contact me through zeke.foxheart@gmail.com or on discord as zeke foxheart #0707

### Additional context

I'll post later if I can think of anything

**Comment by MatrixFrog** [comment]
just wanted to share this in case you hadn't seen it https://www.youtube.com/watch?v=mceaM2_zQd8

**Comment by alexei-kopylov** [comment]
There is another interesting question about this. OK, when n>9 the center ball "escapes" the cube. But is it possible that the _volume_ of the center ball is greater than the volume of the cube? It turns out that yes, but only in n-dimensional space, where n>1204. IMHO, it is very unexpected, and I think it is worth mentioning if you're going to make a video about this topic.

**Comment by ZEKE-Foxheart** [comment]
> There is another interesting question about this. OK, when n>9 the center ball "escapes" the cube. But is it possible that the _volume_ of the center ball is greater than the volume of the cube? It turns out that yes, but only in n-dimensional space, where n>1204. IMHO, it is very unexpected, and I think it is worth mentioning if you're going to make a video about this topic.

The problem is that when the center ball "escapes" the cube, it just escapes parts of the hypercube but will never completely escape it. The issue is that it "escapes" the cube when looking at it in a certain way. I will show a different way to look at what is really going on with the hypersphere and the hypercube.

That is interesting and I can cover why that holds even without the ball escaping the cube entirely or picturing a spikey ball! It almost sounds counterintuitive but it still is true. It also has to deal with the "escaping" aspect of the hypersphere where it makes sense as to why.

**Comment by Graham853** [comment]
I had never heard of spheres being spiky and initially didn't know what this topic was about. I saw the numberphile video, so I know now, However it seemed and still seems to me that it is hypercubes that get spiky in high dimensions, not spheres. A 1024-dimensional cube has 2^1024 corners, each 32 times further away from the centre than the nearest point on the surface, and I call that a lot of spikes!

**Comment by ZEKE-Foxheart** [comment]
> I had never heard of spheres being spiky and initially didn't know what this topic was about. I saw the numberphile video, so I know now, However it seemed and still seems to me that it is hypercubes that get spiky in high dimensions, not spheres. A 1024-dimensional cube has 2^1024 corners, each 32 times further away from the centre than the nearest point on the surface, and I call that a lot of spikes!

This is closer as to which I was going to highlight but yeah. Every dimension adds a new direction to expand in and it all adds up (slowly, but it doesn't stop adding up!) The strange part however is that it still follows the same concept of what goes on with regular 2D and 3D cubes as well on top of that

**Comment by ZEKE-Foxheart** [comment]
I was not able to wait any longer for a collaboration but the learning curve for me was too immense to get it done in 14 days. I am withdrawing
