### ISSUE TITLE
Prime numbers in 4D structure

### ISSUE THREAD

**Issue by fbunc** [leios/SoME_Topics#227]
## About the author

Math/science student that  worked as a teacher (after graduating as an electronic engineer).

Trying to explain non-trivial concepts in a simple visual and intuitive way was the reason why I started doing some animations to make some ideas more manageable. Doing this animations  and watching 3b1b was the spark that gave me some research ideas I started exploring in my free time for the last  years.

## Quick Summary (Edited)

This is a way to draw a map of prime numbers in 3D, and get the feeling they follow orbits in a pattern as if they had some kind of bigger/smaller  "mass" than the others. Notice also how these "orbits" concentrate prime numbers in specific areas of the plot.

Maybe it's better with animations than words:

Starting with a 4D spaghetti : 

https://www.youtube.com/watch?v=LRXt_ddVSFE

Adding then some  more 'matter/numbers/colors' in 8 extending wheels, mirroring the first spaghetti and using diamonds for all prime-positions and stars for the main 'primes-observer' :

Adding gray numbers:

https://www.youtube.com/watch?v=OEYpuI8MvxU

Or collision and 'Correlated-colors'

https://www.youtube.com/watch?v=tzrLZQ6y9ZE

Original proposal

https://www.youtube.com/watch?v=vlELOLepxi0

First introductory puzzle relating golden ratio to  mod 13 wheels:

https://www.youtube.com/watch?v=NY5tgKBtLQ0

A (corrected) open-script-story between two main fictional characters called 'Time' and 'Symbols' : 

https://github.com/fbunc/golden_ratio_mod_13_structure/blob/master/time_and_symbols.md

Why playing with $\phi$ and friends is fun by Math is Fun dot com:
https://www.mathsisfun.com/numbers/golden-ratio.html

Gottfried Wilhelm Leibniz philosophy:
https://plato-philosophy.org/wp-content/uploads/2016/07/The-Monadology-1714-by-Gottfried-Wilhelm-LEIBNIZ-1646-1716.pdf

## Target medium

I'd like to see a better version of this  kind of idea in a video, maybe in another context, and with explanations and formulas making it comprehensible for everyone. 

3D animations skills are welcome. Also if someone using manim could help great. 

Formulas and basic code for animations is provided. Also any further explanations can be provided by email, or added to the github if someone is interested.

https://www.youtube.com/watch?v=vlELOLepxi0

### More details

A github with some basic explanations:

https://github.com/fbunc/golden_ratio_mod_13_primes_disc

The 4D flower raw code and thought process:
https://github.com/fbunc/4D_flower/blob/master/README.md

RAW code:
https://github.com/fbunc/4D_flower/blob/master/eigenwheels_raw_v2.py

### Contact details

fbatrouni at mi.unc.edu.ar

### Additional context

I Reopen this issue, because first time I was in a conversation with neondata and it was late and I got too tired what caused a misunderstanding from my side. 

neondata insights where Brilliant and really useful for me after I red everything again.

The only reason I'm publishing this is to give back and because of my big appreciation   of all the available educational videos online. 

I posted some proposals here, and I made it in a  rush, so my English  was poor (I'm not a a native speaker) and I might have been a little confusing in the way I communicate. So I'm sorry for that, I should have planned better the material I share. Also I didn't have the channel active, and I wasn't planning to activate it, but I reestablished it only for  SoME2 to be able to show my half baked attempts to someone that can understand them or maybe just do cool animations in it's own channel with selected explanations included.

My github now only contains the cleaner versions of my notes. 

Check this map made by Dominic Walliman:
![](https://camo.githubusercontent.com/f3032039e69adc18d74fc95a0edec7867c69475e8c748e6d2bacc49368d5ceb8/68747470733a2f2f692e726564642e69742f7a7a79763266616a626e6b7a2e706e67)

**Comment by neondata** [comment]
![SnSh28 6 2014-14 24 56](https://user-images.githubusercontent.com/3920370/180075859-80b48cff-ce2a-4eb3-8c3c-a9b67f545d65.gif)

There are nice cristalls based on primes.
How do you understand "impedance"?

**Comment by fbunc** [comment]
https://en.wikipedia.org/wiki/Electrical_impedance
Impedance is just the context in witch I got familiar with complex numbers (a+i·b) or like engineers like to write it $R+j·X$.
You can combine impedances in series and in parallel to create, for example, analog filters used in electronics for example. 
A basic impedance is a resistor where a=R ohms 
A pure inductance has a pure imaginary value of $X=j·\omega·L$ 
A pure capacitance has a pure imaginary value of $X=\frac{1}{j·\omega·C$

**Comment by neondata** [comment]
While I can not follow to all you say it looks interesting and I like the map of math that shows that all the topics are interlinked. The concept of "impedance" indeed is mostly used by electr***l engineers, indeed as a HAM I used this in the context of transmission lines: cables, antennas, free space were we have the wave resistance of about 380 Ohm. So it's always about impedance matching and energy transfer. I use this term to describe the ability to transfer energy from one system to another. 
As you seem to think out of the box: The question is: is there impedance at the outside of the universe or does the wave front (light) just create something that can carry itself ;-)  I heard there was something as superexpansion after the big bang where the universe expanded and then shrunk again what could in terms of impedance be interpreted as there is a short-cut or open end of the "transmission line" which is the universe itself we know.
Funny things may come from the impedance.

**Comment by fbunc** [comment]
Maybe you just reverse the order of n and take a look. But that is exactly the feeling of many people playing with these ideas. The ancient book I-Ching (a book that is pseudo-science under the wrong scope) has the interesting property of being written during many generations, and 'reality' was documented following an order, and looking at the constant parameters. Someone in that long chain of generations, maybe added a label to the pages of his professor, and played with the idea of defining a sense of direction of time given your current state of mind and 6 bits

**Comment by neondata** [comment]
If you meant me, I have to admit there a lot of references to a context I don't know .. But do you agree that impedance gives you an insight as it is a measure how something (energy) is a product of something else (voltage) (current)

**Comment by fbunc** [comment]
This video shared to me by someone in discord, gives a great context to all this games, The Unfinished Game Pascal, Fermat:

https://www.youtube.com/watch?v=W5XbuQq65Xc&t=0s

**Comment by fbunc** [comment]
quote user neondata:
"If you meant me, I have to admit there are lot of references to a context I don't know .. But do you agree that impedance gives you an insight as it is a measure how something (energy) is a product of something else (voltage) (current)"

So more latex on the go:

I think you know that for some mysterious reason I always felt puzzled about, when you make a ratio between the magnetic and the electric field , the units happen to be in ohms

**Comment by neondata** [comment]
It will take at least 1/2 an hour to watch the video, but as I like veritasium I'll have a look to see where I agree and where not. As I looked to stackexchange and saw the politeness of the answers, I'm positively surprized. That doesn't happen often when you ask simple questions that look stupid to the "knowing".
The concept of "impedance" is introduced whenever the simple "ohmic law" doesn't apply. That is, when a 2-pole shows changing current when the voltage is constant or changing voltage, when the current is constant. It turns out that three cases are sufficient to describe everything: voltage and current are proportional, voltage change is proportional to current and current change is proportional to voltage. 
As an electrical engineer you know in a resonance circuit energy is stored and continuously changes from magnetical to electrical state. When an antenna is connected, energy is radiated and then electrical and magnetical field are in phase. That is: travelling waves show in phase e-m-fields while in a cavity they are shifted by 90°. So an antenna is something that is able to shift the phase of e- and m- components of the field, but how? Is one shifted by 90°? Are both shifted by 45° into opposite direction, if yes: which one into which direction. At my time we just calculated the near field and the far field, and left the gap open. Maybe now this has changed, but I doubts, otherwise such questions should not arise or answered quickly. So you ask as "kurt"?

**Comment by fbunc** [comment]
> It will take at least 1/2 an hour to watch the video, but as I like veritasium I'll have a look to see where I agree and where not. As I looked to stackexchange and saw the politeness of the answers, I'm positively surprized. That doesn't happen often when you ask simple questions that look stupid to the "knowing". The concept of "impedance" is introduced whenever the simple "ohmic law" doesn't apply. That is, when a 2-pole shows changing current when the voltage is constant or changing voltage, when the current is constant. It turns out that three cases are sufficient to describe everything: voltage and current are proportional, voltage change is proportional to current and current change is proportional to voltage. As an electrical engineer you know in a resonance circuit energy is stored and continuously changes from magnetical to electrical state. When an antenna is connected, energy is radiated and then electrical and magnetical field are in phase. That is: travelling waves show in phase e-m-fields while in a cavity they are shifted by 90°. So an antenna is something that is able to shift the phase of e- and m- components of the field, but how? Is one shifted by 90°? Are both shifted by 45° into opposite direction, if yes: which one into which direction. At my time we just calculated the near field and the far field, and left the gap open. Maybe now this has changed, but I doubts, otherwise such questions should not arise or answered quickly. So you ask as "kurt"?

Sorry, kurt? what is that?

About what you say, it's not clear if you don't know much about these topics as you said, or if you are trying to test if someone else you just met knows what you value as a treasure. I can understand that, that's why so many people jumped against Veritasium in his first video about fields.

In our own minds, we all have different kind of ideas that we feel as treasures, the cool thing these things are always what connect us, not what makes us different/better-lesser-than-each-other/wiser/up/down/flip/flop/send/ack? Real knowledge, Reality (that must be saved) , don't need a concrete definition of polarity , +,-,0,1, it's just a convention.

you know E and B are orthogonal and you where trying to see if I did? Count on that this conversation between us may be understandable to people that are not so familiar to these ideas and break down the basics together. I can tell you I'm more interested on music sequences and how they can be modified using a simple device called muse and generate an animation with my brain-waves, I mean I'm not really  into going deep in subjects are far away of my level of math, I need to take some time on understanding minkowski-time-cones for example, I'm completely ignorant about that but fascinated about the possibility to be able to manage tensors as easy as I deal with complex numbers and transformations in the complex plane. This is just someone that wanted to explain complex things to people that was just beginning with all these subjects, the result? a lot of cool graphics I started sharing with friends because I think they look cool, and  

I have to thank your replies because for me it's the perfect opportunity to see how other people think about these things (what I see just as a piece of art that the big online community,with big heads as 3b1b on the state of the art, inspiring thousends of people to learn and play with math and science ideas). Just check the math on the Shannon Wavelet and see where it takes you

**Comment by neondata** [comment]
I myself closed two issues, one: https://github.com/leios/SoME_Topics/issues/205 which no longer has any content, I decides this after some "moderators" kicked me of discord while I was writing. I only asked: what is the double slit made of? And can you explain why an electron should interfere with itself?  Social media are so strange as they open the world to everybody and as we have seen what happens in the "real world"  I still believed that this was not the case in science, that questions are allowed and "alternative facts" are just the same facts from another perspective. 
So as you are asking questions I also do: can you imagine a switch without losses? Me not. I can only imagine a dooms day switch. Imagine to pinpoints at the end of a wire connected to a voltage source. If you bring the tips in proximity they obviously form a capacitor. Every time the distance is laved, the capacity is doubled and current flows driven by voltage into the capacitor and the energy is stored there. So if you change the distance in such a way, that the current flowing constantly, this setup looks like an ohmic resistor. Only it you widen the gap you will see, that the energy comes back. But: If you one time decide to close the gap, what happens to the energy stored in the cap? It is dissipated. And there is no way to close a contact connected to a voltage source, without dissipating the energy stored in the electrical field between the once separated contacts. This is even true for a semiconductor or a diode. The only ways to limit the losses are to have a resistor in series to limit the current as an R-C-filter or to have an inductance in series for the same purpose, this inductance stores energy and when the contact is closed, this energy will go to the sink.
But you started to plot prime numbers and I showed, that prime numbers can be cristals with defects.

**Comment by fbunc** [comment]
> I myself closed two issues, one: #205 which no longer has any content, I decides this after some "moderators" kicked me of discord while I was writing. I only asked: what is the double slit made of? And can you explain why an electron should interfere with itself? Social media are so strange as they open the world to everybody and as we have seen what happens in the "real world" I still believed that this was not the case in science, that questions are allowed and "alternative facts" are just the same facts from another perspective. So as you are asking questions I also do: can you imagine a switch without losses? Me not. I can only imagine a dooms day switch. Imagine to pinpoints at the end of a wire connected to a voltage source. If you bring the tips in proximity they obviously form a capacitor. Every time the distance is laved, the capacity is doubled and current flows driven by voltage into the capacitor and the energy is stored there. So if you change the distance in such a way, that the current flowing constantly, this setup looks like an ohmic resistor. Only it you widen the gap you will see, that the energy comes back. But: If you one time decide to close the gap, what happens to the energy stored in the cap? It is dissipated. And there is no way to close a contact connected to a voltage source, without dissipating the energy stored in the electrical field between the once separated contacts. This is even true for a semiconductor or a diode. The only ways to limit the losses are to have a resistor in series to limit the current as an R-C-filter or to have an inductance in series for the same purpose, this inductance stores energy and when the contact is closed, this energy will go to the sink. But you started to plot prime numbers and I showed, that prime numbers can be cristals with defects.

Perfect opportunity to drop the right formulas to express what you mean:

You are saying, kids lets consider :

$$Z= R+j(\omegaL-\frac{1}{\omegaC})$$

And lets solve for resonance:

$$\omegaL-\frac{1}{\omegaC} =0$$

I know everybody reading this can arrive to:

$$\omega^2 = \frac{1}{LC}$$

**Comment by neondata** [comment]
Just to post-it:  https://www.youtube.com/watch?v=OFI1FJcGLeM Interesting to watch a scientist realizing what every gear shaper knows : 15:00 .  On the other hand: gear shapes don't imagine there knowledge to be relevant to science.

**Comment by fbunc** [comment]
> Just to post-it: https://www.youtube.com/watch?v=OFI1FJcGLeM Interesting to watch a scientist realizing what every gear shaper knows : 15:00 . On the other hand: gear shapes don't imagine there knowledge to be relevant to science.

Amazing explanations!!, did you see these two Mathologer videos and tried to connect them? for sure many people did

Discrete Newton and what's next? (methods for investigating sequences)
https://www.youtube.com/watch?v=4AuV93LOPcE

Mathologer FlowerPhi
https://youtu.be/_GkxCIW46to?t=54

**Comment by neondata** [comment]
OK, I have to turn a part on my lathe. So let me now pause with an idea: the physical concept "action" (behind the famous quantum of action) in dimension is energy times time. (like impedance: voltage over current) So what is the impedance of action?

**Comment by neondata** [comment]
> Have you seen these two Mathologer videos and tried to connect them?

I've seen a lot and learned a lot or became aware of a lot, but I tried to connect and ask two things but didn't get an answer.

So I can point you to something that to me is a fascinating relationship:

The equation   I^N + J^N = K^N, as we all know has no solution for integers I, J, K, N  if N>2.  The question I rise is: is this equation mathematically equivalent to the question if the function z = f(x,y) = x^N + Y^N  can have the same value z for two 2-tuples (I, J ) and (K, 0)
I raised this question multiple times and never got an answer.

**Comment by fbunc** [comment]
> OK, I have to turn a part on my lathe. So let me now pause with an idea: the physical concept "action" (behind the famous quantum of action) in dimension is energy times time. (like impedance: voltage over current) So what is the impedance of action?

You mean the spooky one? haha

This is getting funny, really I told you. 

My level of particle physics is  just  that I know about electrons as a story I told to myself during my career. 

The double-slit-experiment and "the-observer" collapsing the wave function always sounded great to me but more like the title of a novel, or a simplification-idea-thought-experiment went wild in the wild. 

But as I said, I'm just playing with the ideas the online community shares. We all do that, but if we don't find the right context, good ideas or proposals go to waste because of lack of formality, and I learnt that the hard way.

What  I loved during  my career was control theory and the introductions to signal processing and  dsp (MIT published the bible on all these topics freely available online), so... not really my place to introduce quantum topics/paradoxes .

 Because what I think you just tried to say using the wrong words this:

(now I will use E for energy not electric field)
$E=P·t $ what would be a first simplification of an integral we both know that energy is the area under the curve of the rate on which that energy is generated/consumed during a certain times. This is also related to -work- , usually measured in Joules and E in the context we are talking about, but for people not familiar with this I simplify saying that E units are what you pay for your $kWh/month$

**Comment by neondata** [comment]
As an electrical engineer you learned different concepts.As a physicist you would have learned about the same topic from a different view point. As a mathematician you learn about abstract structures and there is no need to apply them to anything if only you are paid ;-) 
So I can show you something that should be an eye opener if they are not open already. To prepare it: do you know the Clarke-Park transform? And if yes, can you tell me with simple words what it means ? (Just to synchronize)

**Comment by fbunc** [comment]
Nope, you sent me to google:
https://es.mathworks.com/solutions/power-electronics-control/clarke-and-park-transforms/_jcr_content/mainParsys/band_copy_1227855798/mainParsys/columns_1606542234_c/1/animation.animation.mp4/1614705044699.mp4

**Comment by neondata** [comment]
My solar panels work for me just now! 20 kWp, 3ph, but I plan to develop a 48V system to have every  panel MPP-tracked and go to a 48V battery to then drive a heat pump at winter time. Do you work professionally in this field. 

So I googled https://www.youtube.com/watch?v=9jBwIlTEa9M as a short video not to waste your time. As you may follow the math, (not the money) you will for sure miss a deeper insight. I'll come up with this later..

**Comment by fbunc** [comment]
Really? heat pump? I trust you know how to calculate the PV power you need given your simulated/measured load profile and local irradiance profile,you should know what you are doing. Now I go to sleep, I hope this conversation helps someone learn new topics. I think I'll be out of the internet for a while to finish some work, but great to meet you, and I also come back later. cheers

**Comment by neondata** [comment]
You worked as a teacher and did you ever laugh about someone who knew less then you do? So why should anybody care about being laughed at. OK with the heat pump: 1kW electricity in average creates about 4 kW of heat. You have to store the heat in a "(thermally) stratified storage tank" (hard to even find the english expression to the well known "Schichtspeicher") As solar power on your roof is for free (you can feed it to the grid for 0.08€/kWh) such a solution is just fine. I produce about 25 MWh a year. 
So if there is around a person who can explain the Park-Clarke-Transform in simple terms and why it is used as it is, reading this conversation, jump in and answer the question raised :-)

**Comment by fbunc** [comment]
> You worked as a teacher and did you ever laugh about someone who knew less then you do? So why should anybody care about being laughed at. OK with the heat pump: 1kW electricity in average creates about 4 kW of heat. You have to store the heat in a "(thermally) stratified storage tank" (hard to even find the english expression to the well known "Schichtspeicher") As solar power on your roof is for free (you can feed it to the grid for 0.08€/kWh) such a solution is just fine. I produce about 25 MWh a year. So if there is around a person who can explain the Park-Clarke-Transform in simple terms and why it is used as it is, reading this conversation, jump in and answer the question raised :-)

I think this conversation is not being productive, I meant no disrespect. I thought this was open to teachers, I was one and a very good one.I'm happy I was able to inspire many students  that knew I was there to help, to reduce the complexity of the things written in the books and in the things they don't understand. 

Some of them lost respect and where more stuborn than me, those I respected and leave space , but I do not enjoy confrontations, nor competitions, and we all get the "discovery" you are hinting, I'm doubting if you are just trying to be rude or what. But please, just go on research and elaborate your ideas further. I just said I'm going to sleep because I'm really tired and using the internet long hours it's not good for help.

Hope we all can respect eachother, despite differences.

Thank you

**Comment by neondata** [comment]
sorry, I in no way intended to embarass you, Maybe it's using a foreign language or even bad experience, I had enough myself.

**Comment by neondata** [comment]
What I wanted to show is: knowledge is not less worth, when it turns out to be not sophisticated. The opposite is true. Progress is reached when knowledge can be aquired by more people. In the past it was the privilege of an elite to read and write, this is no longer the case and so we can communicate.
So now let me show you what is the secret of the Clarke-Park transform: from 3 sinusoidal voltages or currents you create a single sinusoidal voltage/current (Clarke) and then a DC voltage current (Park). 
What we need is Kirchhoffs law: ths sum of currents/voltages is zero. So e.g.  U+V+W = 0. Then U*1 + V*1 + W*1 = 0. We can write this as the inner product of two vectors: (U, V, W) * (1, 1, 1) = 0. All vectors with an inner product of zero are perpenticular and all vectors perpenticular to a given vector are in a plane. You can designate the axis of this plane as X, Y, or d, q. If you take the phase angle of U as a reference, and line it with the d-axis, the vector formed by the 3 values (often called "space vector) lies in this d/q plane. And that's it, without any imaginary number and matrices.

**Comment by fbunc** [comment]
> What I wanted to show is: knowledge is not less worth, when it turns out to be not sophisticated. The opposite is true. Progress is reached when knowledge can be aquired by more people. In the past it was the privilege of an elite to read and write, this is no longer the case and so we can communicate. So now let me show you what is the secret of the Clarke-Park transform: from 3 sinusoidal voltages or currents you create a single sinusoidal voltage/current (Clarke) and then a DC voltage current (Park). What we need is Kirchhoffs law: ths sum of currents/voltages is zero. So e.g. U+V+W = 0. Then U_1 + V_1 + W*1 = 0. We can write this as the inner product of two vectors: (U, V, W) * (1, 1, 1) = 0. All vectors with an inner product of zero are perpenticular and all vectors perpenticular to a given vector are in a plane. You can designate the axis of this plane as X, Y, or d, q. If you take the phase angle of U as a reference, and line it with the d-axis, the vector formed by the 3 values (often called "space vector) lies in this d/q plane. And that's it, without any imaginary number and matrices.

I just think that with imaginary number all makes more sense and its really easier. Complex numbers are not complex at all

**Comment by leios** [comment]
Sorry I saw this conversation so late. @fbunc Would you say that @neondata is going far offtopic for this thread?

**Comment by fbunc** [comment]
I think we all agree this conversation served it's purpose. Thanks

**Comment by leios** [comment]
Ok, good. I realize that this discussion is quite offtopic and might discourage people from actually collaborating on this post. I can delete the comments on this thread so that people do not see the spam, if you want. Otherwise, we can leave it as is.

**Comment by fbunc** [comment]
I think this is just a classic classroom situation, just that

**Comment by neondata** [comment]
Do whatever is needed

**Comment by fbunc** [comment]
I will publish a more organized Idea sonn, thank you neon and leios and sorry if any fuzz. my lema is -omit-drama- . Peace

**Comment by fbunc** [comment]
I Reopen this issue, because first time I was in a conversation with neondata and I got too tired and that caused a misunderstanding from my side. Neondata insights where brilliant, and really useful, and also one of latest Sabine videos was a great introduction to some of neon questions. Next proposal I'll try to include some MIDI music in the same sequence, maybe some musician jumps to the rescue.

**Comment by fbunc** [comment]
Please @leios delete everything here. Posting a clean version with a summary. Thank you
