### ISSUE TITLE
Software engineer in creating visual and interactive games/web applications.

### ISSUE THREAD

**Issue by ManukMelkonyan** [leios/SoME_Topics#228]
## Portfolio

I am a computer science student from a little country called Armenia.
I am interested in making interactive games/web applications about math/science/computer science.
Below you can see one of my personal projects - A pathfinding and maze-generating visualizer (based on the most famous graph algorithms).
[Github - PathFindingVisualizer](https://github.com/ManukMelkonyan/PathFindingVisualizer)

## Target topic categories

Highly motivated in creating visualizations for algorithms, numerical methods, etc.

## Target medium

I would like to participate in creating an interactive game/application.

### Contact details

Email: myan.manuk@gmail.com
Linkedin: [manukmelkonyan](https://www.linkedin.com/in/manukmelkonyan/)

**Comment by Rami5743** [comment]
Hi,

The following issue might be relevant:
https://github.com/leios/SoME_Topics/issues/234#issue-1327090293

See you

**Comment by NerdToMars** [comment]
https://github.com/leios/SoME_Topics/issues/235 something related to CNN and object detection https://poloclub.github.io/cnn-explainer/
