### ISSUE TITLE
I wrote a program that finds periodic solutions to the N-body problem

### ISSUE THREAD

**Issue by gabrielfougeron** [leios/SoME_Topics#23]
## About the author 

I work as a research engineer in numerical methods (discretization of PDEs, optimization, ...) in the industry.

## How the topic came to be

In the very beginning of my PhD, I came across a large body of academic work on "N-body choreoographies" : http://www.scholarpedia.org/article/N-body_choreographies .

In short, those are solutions to the Newton equations of motion for N gravitationnally interacting bodies that all follow the same trajectory, and loop periodically. I instantly found them beautiful and fascinating.

In particular, I spent an unreasonnable amount of time playing with Gregory Minton's choreography finder: http://gminton.org/#choreo and reading his PhD thesis on a related subject ( https://dspace.mit.edu/handle/1721.1/84405 )

... and a few years later I started building my own solver.

This is how I wrote a python program (available at https://github.com/gabrielfougeron/Choreographies2 ) to more generally find periodic solutions of the Newton equations for N bodies that interact in a central (i.e. rotationally invariant) potential. The code is a bit messy, and not well documented, so I gathered a few examples of what the program can produce here:

https://gabrielfougeron.github.io//SOME_videos.html

## Technical possibilities and limitations of the program

Even if all the videos I show on the website show 2-dimensional motion, the solver itself is n-dimensional. I can thus try and find 3-D solutions. I have never gotten arround to doing it however, mostly because the 2-D world is extremely vast already and also because I don't really know where to start in terms of 3-D visualization. n-D with n> 3 is (theoretically at least) possible as well, even if the visulalization challenge is even greater.

## What I initially wanted to achieve

The end goal has always been to simply see and create those beautiful animations, and this is why I created the program.
In order to read some kind of an audience, I've also started to create a GUI for this program, but it is nowhere ready yet, and will certainly not be for mid-August.

Maybe with the help of someone else, those beautiful images can find a larger audience.

## What could happen with SOME

I have never tried to create an explainatory video or blog post or anything like that. But if anyone thinks like me that N-body choreographies are beautiful and wants to invest time in creating any kind of beautiful / engaging educational content on the topic, I'd be ready to invest time and help them use my python scripts, and / or explain the math that goes into finding such solutions.

## What I am looking for

A person who thinks choregrapies are beautiful and who is motivated to create something arround them. I would provide the mathematical expertise and the python program, and they would provide the rest, i.e. the storyline, the narrative, most of the creative ideas, the writing, the video production / editing skills etc ...

I'm open to ideas, feel free to contact me if you are inspired

## Contact details

I will follow Grant Sanderson's idea and propose people come in contact with me through Github issues on the Choreographies2 repo : https://github.com/gabrielfougeron/Choreographies2/issues , or just comment under this post.

## Additional context

Currently, the python program is under a very permissive BSD 2-Clause License. I don't know much about licencing so this could change if needed.

**Comment by mathelehrer** [comment]
Sounds like fun. What I can offer is sketched in issue #4. Let me know, whether there is some overlap.
Johannes.

**Comment by gabrielfougeron** [comment]
@mathelehrer : Looks super cool! As I mention in the post, I don't have a narrative / story ready yet, nor do I plan on making one up on my own. Maybe we could do a 3-people collaboration?
