### ISSUE TITLE
Seeking detailed knowledge of the Gödel Incompleteness Theorems

### ISSUE THREAD

**Issue by Omnicate-Replibus** [leios/SoME_Topics#27]
### Context

For a while now I've wanted to make a YouTube video essay about Gödel's Incompleteness Theorems, aimed at non-mathematicians, which would give a clear idea of how they work and why they're so important. The Veritasium video on this topic does a stellar job at teeing up concepts and explaining context, but in my opinion falls short of explaining _why_ or _how_ the Godel sentence is able to assert that the theorem with its own Godel number is unproveable. I believe that with the right approach, this can be explained to a lay audience, and I'd like to try.

### What I'm Looking For

I'm looking for somebody who knows more about the Theorems than I do. I'm familiar with them on a pop maths level - I've read the Nagel & Newman book, and I've taken a course in mathematical logic, so I'm relatively sound on the fundamentals. That said, in order to make sure I don't say anything that's wrong or misleading (specifically with regards to the distinction between language and metalanguage) I would like someone who'd be willing to proofread my script when it's finished (which won't be for a few weeks yet, my finals loom on the horizon), and maybe consult with me a few times while I'm putting it together.

### Contact Details

I can be found here on GitHub, or you can email me at katielepoidevin@gmail.com. My Discord handle is Omnicate Replibus#0629 and I'm on Instagram at @katiemathpunk.

**Comment by ChristopherKing42** [comment]
I could do some proofreading, although you might want at least one other person (this stuff gets tricky for sure!).

Also see https://www.quantamagazine.org/how-godels-incompleteness-theorems-work-20200714 which is pop sci but also goes into the "how" in pretty good detail.

**Comment by nickmaleki** [comment]
Great topic choice! I've been working on an extension to Godel's incompleteness theorems for the past couple years and I've learned quite a lot. I have a Masters in Computer Science and have in-depth knowledge of quite a few topics surrounding the incompleteness theorems, like LISP, Lambda Calculus, and Mechanical Computability. 

Feel free to reach out on Discord, anick#0001

@ChristopherKing42 I emailed you a link to something I'm working on related to this. If you get the time to look it over, I'd really appreciate it 😁

**Comment by arielCheng218** [comment]
@Omnicate-Replibus Not an expert, but you might want to take a look at the book Godel, Escher, Bach by Douglas Hofdstader as a reference for how to explain this topic. He does an excellent job of explaining why the theorem is important and fundamental. It's also just a really good book.

**Comment by leios** [comment]
Hey @arielCheng218, we have actually moved this repo to the #project-ideas channel on [discord](https://discord.gg/36TVuWQd7Y). Feel free to go there for futher discussion!
