### ISSUE TITLE
Can we recast AI problems as geometric ones? / An applied introduction to geometric group theory and combinatorics

### ISSUE THREAD

**Issue by tfburns** [leios/SoME_Topics#30]
## About the author

I'm a PhD student studying mathematical/computational neuroscience and AI. My collaborator on this project from the academic side is a lecturer in pure math. I tried working on something for last SoME but ran out of time trying to 'prettify' my very unpretty PPT files, so it would be great to have someone with a complementary skillset to work with.

## Quick Summary

How can we represent a typical AI environment using a single geometric or topological object? And if we could, what would it tell us?

This lesson aims at introducing tools and concepts from geometric group theory and combinatorics via a demonstration of their application in simple AI environments called gridworlds. For a high-level (and slightly more academic explanation), see here: https://twitter.com/tfburns/status/1531442853699670017.

The target audience for the SoME project would be high schoolers and early math/AI undergraduates. I'm hoping they will (1) be introduced to classical and new results in geometry (and be introduced to the fields of geometric group theory and combinatorics), and (2) be inspired to see how these results can be applied in exciting and unexpected ways in emerging fields like AI.

## Target medium

The target medium should probably be a moving picture, ideally a video. An interactive webpage could also work, but there would be some computational limitations on what we could show, most likely, and so probably not well-suited for this project. It would be great to make some nice animations of gridworlds (inherently simple 2D environments, much like basic video games) and some useful 3D pictures of graph-like objects called complexes.

### More details

Twitter thread: https://twitter.com/tfburns/status/1531442853699670017 (could be used as a rough guide/storyboard for the video, but ideally we'd add some more technical details about cube complexes and such)

Academic paper: https://arxiv.org/abs/2201.06274 (no need for you to fully read or understand this, as I will be more than happy to, but just FYI -- and the appendix of this paper has some background information on cube complexes and Gromov's Link Condition which should probably go into the video)

### Contact details

Please contact me via Twitter (tfburns), or find my e-mail on my website: tfburns.com

### Additional context

There is a GitHub repository with some tools for constructing simple gridworlds and their associated geometric objects: https://github.com/tfburns/State-Complexes-of-Gridworlds/

**Comment by Shiviiii23** [comment]
Hello! I would love to help with this

**Comment by Shiviiii23** [comment]
Hi @r3dapple I did not get any notification .. maybe email would be better .. my email is shivirevuru@gmail.com

**Comment by Shiviiii23** [comment]
Hello! I was wondering if you could give me your email address @tfburns

**Comment by tfburns** [comment]
@Shiviiii23, please find my e-mail on my website or contact me via Twitter. I would prefer not to post my e-mail here.

**Comment by tfburns** [comment]
Although a few people responded as coming/not coming, no one showed to the video call today.

Unfortunately I have quite limited time for such meetings at the moment as have some conferences and meetings planned up until early August. Please e-mail me directly if you are still interested after reading the paper.

**Comment by r3dapple** [comment]
@tfburns Please check your email. The call was scheduled for 3pm JST, which is in 23 minutes.

**Comment by tfburns** [comment]
@r3dapple Just sent you an e-mail.

**Comment by tfburns** [comment]
Embarrassingly, I mis-scheduled the meeting time on my calendar. Fortunately, @r3dapple indeed correctly pointed this out and we just had a wonderful chat :) I'll close this now since it seems we have a team. However if other wish to join us feel free to reach out.

**Comment by tfburns** [comment]
As a small conclusion to this story: there was some initial interest and conversations, but this ultimately didn't lead to a video/animation/explainer article.
