### ISSUE TITLE
3D animations in Blender

### ISSUE THREAD

**Issue by mathelehrer** [leios/SoME_Topics#4]
![mandel](https://user-images.githubusercontent.com/76424732/172774420-e2f2912e-39c2-4bec-8b82-ade313ad71a4.png)

## About the author

Over the last year, I created a tool that uses blender as a rendering engine. In spirit it is a tiny little clone of the manim library. The advantage of blender is that it is intrinsically three dimensional. I used it in the context of complex functions and in the context of polytopes before.
If you want to see an example, please have a look at:
https://youtu.be/h8WmOXcMwZ0
or other recent videos of this channel.

More short clips:

complex functions: https://www.dropbox.com/s/a6g212gr7bvtcyj/zeta_continuation.mp4?dl=0
polyhedra: https://www.dropbox.com/s/zjfgbl6na9c5ibo/poly_full.mp4?dl=0

I'm working as a high-school teacher. I will have six weeks of summer holidays and lots of time to be creative. I'm not a native English speaker, therefore my contribution to the collaboration should be restricted to the visual content. I have some background in math and physics, which should make the communication a lot easier.

## Quick Summary

everything related to 3D content

## Target medium

video

### Contact details

physik.martin@gmail.com

**Comment by blakesims** [comment]
#39

**Comment by blakesims** [comment]
Hi there, you might be interested in my project involving complex contour integration #39

**Comment by mathelehrer** [comment]
Hi, yes, there might be the possibility to contribute with blender animations. Have you seen my second video on primes. This image is one screenshot out of it. I also should be able to generate vector fields. However, I'm not sure, whether the topic will be overly exciting. From my experience, physics does not perform well on SoME😉I guess residues turn into charges? What highlights do you plan for the story and what special effects could make the video interesting? I'm curious to here a few more details, Johannes-------- Ursprüngliche Nachricht --------Von: blakesims ***@***.***>Datum: Do., 9. Juni 2022, 16:17An: leios/SoME_Topics ***@***.***>Cc: NumberCruncher ***@***.***>, Author ***@***.***>Betreff: Re: [leios/SoME_Topics] 3D animations in Blender (Issue #4)
Hi there, you might be interested in my project involving complex contour integration #39

**Comment by mathelehrer** [comment]
Let's go

**Comment by alexandru-duca** [comment]
This is the result of our video project: https://youtu.be/_hmNwG7Ppyo
