### ISSUE TITLE
A video to get to the bottom of Simpson's Paradox

### ISSUE THREAD

**Issue by eagereyes** [leios/SoME_Topics#43]
I make videos about data visualization research (including my own, I'm primarily a researcher/developer, videos are a hobby). I've been wanting to make a really clear explainer of Simpson's Paradox for a while. If anybody wants to collaborate, I'm happy to make the visuals and create the video. My style is all motion graphics and I aim for videos in the 5-15 minutes range.

## Portfolio

My YouTube channel: https://www.youtube.com/c/eagereyes

I've also done one in a similar style with my head floating in a corner: https://www.youtube.com/watch?v=GeRgED7LWr8&t=4s

## Target topic categories

Simpson's Paradox :) But also open to other topics that are at the intersection of data/data visualization and math

## Target medium

Animated video in the style of my channel

## Contact details

You can find me on Twitter: https://twitter.com/eagereyes

Also, my website has a contact form: https://eagereyes.org

## Additional context

If it matters, I work in a program called Cavalry for the graphics. I want to bring more high-quality data and data visualization-related content to YouTube. I've been blogging about data vis for over 15 years and started my YouTube channel a couple of years ago to branch out – and also because I feel like there's a lot of potential value for using animation and motion to explain data-related topics more clearly.

**Comment by eagereyes** [comment]
I know it's simple, but it's a common thing to find in data analysis (there are also some related topics about sub-group inversions when you slice data). And it's so counterintuitive that they call it a paradox! It's not even paradoxical, but it's still hard to wrap your head around. So I'm hoping to find a way to make it easy to understand and to remember how it works and why.

**Comment by donno2048** [comment]
All I'm saying is that you don't need an "expert" for that one, I mean you know what the paradox is and the reason it "works", and I don't see any way to add more info about it (maybe other than a vector-based illustration which requires prior knowledge from the viewer)...
