### ISSUE TITLE
What is personal dream reality?

### ISSUE THREAD

**Issue by kamiloze2004** [leios/SoME_Topics#49]
## Discussion

A clear and concise description on how to improve this repository, please. Lucid Dreaming is come easy to me, and I don't remember because it is automatic. How to explain personal reality in mathematical language, and what is General Model of Reality?

**Comment by leios** [comment]
Unfortunately, I will have to close this issue unless you can provide more information, like...

What do you mean by "General Model of Reality"? Are we talking about simulating individual events? How we perceive such events? The likelihood of certain events appearing in a dream? Note: if your answer is "everything," this goes beyond the scope of modern mathematics, so far as I am aware. In this case, the issue must also be closed

In addition, we need to know more about what type of project you are envisioning so people can actually tangibly collaborate with you for SoME2.
