### ISSUE TITLE
Animator seeking expert with video idea

### ISSUE THREAD

**Issue by BenjaminGustafson** [leios/SoME_Topics#53]
Hi! My name is Ben, and I am a 4th year math and computer science undergraduate student. I would like to contribute mainly to the graphics of a video project.

## Portfolio

Here are some screenshots of graphical projects that I made using Processing. Processing is the graphics library I am most familiar with, and I think it would be a good tool to make 2D or 3D math animations. I am open to using other tools like Manim, which might be needed to get nice latex rendering.

A complex function grapher.
![complex_sin](https://user-images.githubusercontent.com/47231999/172886831-21f21942-4269-4861-8793-3a6a7de86c7a.png)
Procedurally generated Mondrian art.
![mondrian](https://user-images.githubusercontent.com/47231999/172888915-3267abd6-32b1-40c0-9d93-99f6de81bca7.png)
A visualization of recipe data.
![data_vis](https://user-images.githubusercontent.com/47231999/172889928-c695df8c-3a07-4b69-818a-09219f69f071.png)
A particle system.
![particle_system](https://user-images.githubusercontent.com/47231999/172889939-3010cbd4-7ddd-4628-8ffe-cf3e6fb387e3.png)
Ray-marched 3D Fractals.
![3d_fractals](https://user-images.githubusercontent.com/47231999/172887539-c7d61773-0c43-45f4-bcfe-1f6ac7576408.png)

## Target topic categories

Some topics that I would be interested in visualizing:
- theoretical computer science
- group theory
- graph theory
- topology

I am open to other topics.

## Target medium

I would like to produce a video, although I have little experience in video production, editing, or narration. A collaborator willing to help with that side of video production would be ideal.

### Contact details

My email is bgustafs@trinity.edu.

**Comment by kamiloze2004** [comment]
#38- I need you to my group.

**Comment by hahnfrederik** [comment]
Hi Ben,
I may have a graph theory idea that you could like. I'll send you an email!
Best,
Frederik

**Comment by tjayaram811** [comment]
Hi Ben,

I have an idea about light, waves and maxwells equations that I would love to collaborate on the animation for a video. Please check out #90 and let me know if you are interested.

Thanks,
Tejas

**Comment by aargup934** [comment]
Hi, I have an idea for combinatorics in #18, it would include stuff like graph theory and ramsey theory, I will email you for more details.

**Comment by ArleyGutarra** [comment]
Hi Ben! 
First of all, I think your work is really cool (I loved the 3D fractals). Concerning the collaborations, I had an idea related to analysis on R^n and which in the explanation involves a couple of essential (but core) ideas from topology. It's about the Implicit Function Theorem. I sent you an email. Please, let me know if you're interested

**Comment by rudrathegreat** [comment]
Hello Hello! My name is Rudra Sekhri and I'm a high school student from Australia. Before I jump in about the topic I'd love to collaborate with you on, I just wanted to say that those illustrations up there are super cool! My topic (which you can find here #138) is all about trying to explain the essence of composite functions using ducks and duck eating dragons! Would love to collaborate with you!

**Comment by BenjaminGustafson** [comment]
Will be working with @hahnfrederik.
