### ISSUE TITLE
The math behind decision trees - Machine learning tree-based models in general

### ISSUE THREAD

**Issue by MathiasValla** [leios/SoME_Topics#54]
## About the author

Hi! I'm Mathias, a 2nd-year Ph.D. student in Lyon, France. I study machine learning models and I'm focused on survival analysis and tree-based models (CART, random forests, boosting, etc...). And I think that the latter would potentially be interesting to present pedagogically, with insights, a bit of math, and concrete examples. That's why I'm looking for a collaborator that could produce animations with manim, around that subject. I would also be very curious to learn manim skills from that experience/collaboration and would be delighted to bring math knowledge to the collaborator if that is something that you seek. :)

## Quick Summary

It seems to me that decision trees is a subject that is kind of easy to grasp visually, yet it is not as known as one might think. the idea would be to talk about the history of such models, how they work, a lot of visualization about their construction, and the insight they provide on data. And from there maybe add some content on random forests and boosting? 
The target would be anyone interested in computer science and Machine Learning "simple" models regardless of their background. The audience should be able to understand at least the main ideas behind such recursive models and what their advantages and limitations are.

## Target medium

The idea is to produce an animated video around that topic, over which I could add my voice. The narrative should be one of the most important aspects of the video, and the subject being very "visual", the narrative would benefit A LOT from the animation.

### More details

I will not have all my time for that project but can work on it on some evenings and weekends, and occasionally during the week, but I still intend to produce quality content if I can! 

### Contact details

If interested in that topic, don't hesitate to send me an e-mail here: mathias.valla@gmail.com

Thanks for reading!

**Comment by kamiloze2004** [comment]
The cool

**Comment by yaqoub01** [comment]
Hi I am a second year data science student. I have some knowledge on decision trees and random forests. This summer I planned on looking deeper into the math behind the models I learned in class so if you guys still have room I am interested in the topic.
