### ISSUE TITLE
Quasicrystals - Number Theory meets Physics?

### ISSUE THREAD

**Issue by cmh231** [leios/SoME_Topics#57]
## About the author

Hey! I'm Calvin, I'm a third year physics student at Cambridge in the UK. My main focus when learning physics has always been to build as deep an intuitive understanding for it as possible, and over recent years, I've enjoyed looking into what makes for a good introductory explanation of a topic. I didn't take part in SoME 1, but did take part in Veritasium's physics video contest, and _boy_ am I glad to be free from the constraint of fitting everything into a single minute!

Information on me relative to this particular project - I just finished a research review on quasicrystals which was written with the sole aim of providing as much intuition as possible. I won't pretend to have a complete understanding on the complete depth of maths in the field (although this I will at most mention in passing), I have maths student friends who can ensure that I'm at least not blatantly misrepresenting anything!

## Quick Summary

Quasicrystals are a class of crystals long assumed to be impossible, classified in part by a dense Fourier spectrum, and which often demonstrate properties which would normally only be expected from higher-dimensional materials. This apparent higher dimensional nature arises from the fact that many classes of quasicrystals can be mathematically described based on a slope in a higher dimensional space, characterised by an irrational gradient, with the properties of the quasicrystal being deeply related to its continued-fraction representation. With this in place, we can quickly find that the most pathological quasicrystal we can create in this way is that where the slope is related to the golden ratio, which is directly related to properties of the golden ratio. The multidimensional nature can also be directly linked to an interesting and incredibly discontinuous transformation over the a particular field - the algebraic conjugate, which provides additional interesting information, and for anyone with interest in visualisations of measure theory, details of this arise both here, and in the spectrum (which is, as one might expect, by now, deeply related to the properties of the golden ratio).

In short, through the lens of building a quasicrystal to explain order found in nature, we can explore and visualise some interesting number theoretic properties on the irrationality of the golden ratio, as well as explain why these materials seem to behaviour as though they exist in a higher dimension - purely through a neat mathematical representation!

## Target medium

My original thought was to produce a video on the topic, but I'm happy to be persuaded over to other media (assuming that the bulk of the communication would not be through standard paragraphs of text).

Primarily, I'm looking for someone with experience in animation, since a lot about this topic lends itself to a visual presentation, but as long as the mathematical ideas can be visualised with some degree of accuracy, I'm very happy to be flexible with the format, and an interactive handling of quasicrystals could be amazing. To help this along, I'm definitely able to produce static mock-ups of the concepts we'd be trying to explain through animation, as well as producing detailed story-boards and scripts (depending on how much freedom you would want) from which to work.

In terms of your involvement, the things I'm necessarily looking for are the ability to help me convey ideas through graphics (i.e. probably animation, although interactive stuff would also be amazing!!!), and compile what we've made into the final product (i.e. editing, in the case of a video, or creating a website if we choose to do that). Additionally, I would hugely value another set of eyes looking at how this is structured, and any such feedback would be greatly welcomed! However, if you want more involvement in the physics/maths side, the writing side, or anywhere else, I'd be excited to be flexible and get you on board with other parts, too!

### More details

Whilst I don't have it hosted anywhere online, and am not certain if I want to host it publicly, I would be more than willing to share the research review which inspired this (although please note that it is _not_ my intention to include large sections of that review in the video).

As for story-boarding, or the like, I would expect we would be generating much of this in collaboration, and so I wouldn't want to put forward anything more fixed, now. However, over the coming days, I may add to this with a rough storyboard, although, as mentioned above, this would be primarily to describe the rough details I would like to cover.

### Contact details

I can be reached most easily via Discord (DoublyNegative#6066), or via email (cmh231@cam.ac.uk).

### Additional context

Whilst I have a fair body of papers collated for this, two major inspirations for sections of this are [Luck and Petritis](https://doi.org/10.1007/BF01127714) and [Baake and Grimm](https://doi.org/10.1107/S2053273320007421). I should add for fair warning that I have not, at the time of writing, delved _completely_ into all of the proofs which I plan on covering in this, but I would say I _do_ have a complete understanding of the ideas required for anything I plan on discussing in detail, as well as how they would be proven, and those parts which I have not covered in detail myself I either know roughly how to prove, or know where to look for a proof (since my research into this topic began for a research review, this was all necessary and assessed in my viva, if that helps give any reassurance as to my competence).

**Comment by kamiloze2004** [comment]
Krystal Ratio not Golden Ratio because it is in "Proposing A "New" Cosmology Beyond Death Science," this book help me understanding universe better than if I don't have it and #38 will be a general mathematics.

**Comment by kamiloze2004** [comment]
Krystal Ratio is y = 2^x

**Comment by cmh231** [comment]
Am closing this thread as I've now found a content producer. Thank you _so_ much to everyone who's reached out to me - it's been amazing and humbling to see the cool stuff everyone's already gotten up to, and I really look forward to seeing what everyone achieves!!!
