### ISSUE TITLE
Intro to Quantum Computing

### ISSUE THREAD

**Issue by zimmermant** [leios/SoME_Topics#67]
## About the author

I'm a professor of physics at the University of Wisconsin - Stout.  I'm involved in integrating computational modeling into undergraduate courses and recently got involved in integrating quantum computing into the undergrad physics curriculum.  

I also wrote a series of tutorials on using manim back in 2018 but never had enough time to create any content videos.

## Quick Summary

As an entry point to understanding the math behind quantum computers, I want to show how vectors and matrices can be used to model classical logic gates in more familiar circuits.  I think there is a lot of insight that can be had from looking at the mathematical representation in a classical setting, which allows you to start to view classical logic gates as vectors.  I think this opens the door Hilbert spaces.

My target audience is people who've had some undergraduate math, physics, or computer science courses.  I'd love to create a series of videos that could be a companion to an intro to quantum computing course in the same way that the Essence of Linear Algebra is a great companion to a course in linear algebra (I actually use EoLA when teaching intro to qc).

I'm open to other quantum computing-adjacent topics, but I view this as a good point of entry to the wider world of quantum information science.  My ultimate goal is to disprove Feynman's too-often-quoted "nobody understands quantum mechanics".

## Target medium

I'm looking to for help creating a video (or videos) in manim or blender.

### More details

I haven't written anything up about this due to just not having enough time.

My very very rough outline is:
1) What is a classical logic gate
2) The truth about truth tables
3) Fun things to do with gates
     a) Full of adders
4) Bit Basics
     a)Bits as vectors?!
5) Matrix mania
     a) Turning truth into math
6) What does it all mean?

### Contact details

Reply to this topic, or via email at zimmermant@uwstout.edu

### Additional context

(Is there any other relevant information? Additional sources pertinent to the discussion?)

(Any additional licensing information? If you do not say anything, this post will be considered [CC-BY](https://creativecommons.org/licenses/by/2.0/).)

**Comment by kamiloze2004** [comment]
How to make Quantum Code into Classical Computer, if you answer the question you all join #38.

**Comment by GutagiGit** [comment]
Hey, I am an 16 years old highschool student, I have some experience with manim and blender, and would like to collaborate with you. I know about classical computing and logic gates but not really about quantum computing, but I would love to learn about it.

**Comment by farbowitz** [comment]
I'm actually going into a PhD involving inverse design to (in part) work with photonic logic gates generated from nanoscale fabrication on silicon.  I'm curious if this is something you've come across this in your field. I'd also be happy to help contribute to the content.

**Comment by zimmermant** [comment]
> 

@GutagiGit Do you have links to examples of videos you put together?

**Comment by farbowitz** [comment]
@zimmermant Cool! Happy to connect on this, are you on the discord?

**Comment by zimmermant** [comment]
@farbowitz I am on discord.  User name: tzimmerman#6132
