### ISSUE TITLE
Golden Ratio / Phi Video

### ISSUE THREAD

**Issue by justingolden21** [leios/SoME_Topics#69]
## About the author

Hi, I'm Justin Golden. I graduated from SDSU with a degree in computer science, currently work in San Diego as a web dev. I'm not the best at math, but I was obsessed with the golden ratio as a kid and think I could make a killer video if I found a skilled partner willing to work with me : )

## Quick Summary

Target audience is pretty wide. I'd ideally like to aim at younger audiences, so that even someone 12, 10, or 8 could walk away with some understanding.

## Target medium

Likely a video.

### More details

N/A

### Contact details

JonnyG21#2641 is my discord name, I can also provide my phone number if you'd like.

### Additional context

I may also be interested in making a video on computers adding numbers. A lot of good ones exist but I think I could explain it really well if I research a lot and get really good animations. Just an idea.

**Comment by kamiloze2004** [comment]
Krystal Ratio is x^y, Golden ratio is phantom ratio and Krystal ratio is natural ratio.

**Comment by justingolden21** [comment]
Found someone : )
