### ISSUE TITLE
Probability and Expected Value of the Pyramid Dice Casino Game

### ISSUE THREAD

**Issue by kjlubick** [leios/SoME_Topics#72]
## About the author

I am a software engineer and adjunct instructor in North Carolina, USA. I am a recreational mathematician and strive to teach with clear, concrete examples. I've been known to (ab)use spreadsheets as a way of giving these worked examples for abstract ideas. [Neural Network Backpropagation](https://www.youtube.com/watch?v=fjfZZ6S1ad4) and [Image Recognition](https://www.youtube.com/watch?v=8QfFtUcuYCU) are two of [several](https://www.youtube.com/watch?v=fjfZZ6S1ad4&list=PLDs5gxU1J5CIt5kIiQLC3RBOAKnUAo412) things I have implemented in spreadsheets to help explain the concepts.

My explanatory medium of choice has been Google Slides, which is serviceable, but a little plain for some things.

## Quick Summary

I came across an old game called [Pyramid Dice](https://www.bizjournals.com/denver/stories/1998/08/10/smallb1.html) in Mark Bolman's Textbook _Mathematics of Casino Carnival Games_ and thought it really neat. 

![Screen Shot 2022-06-09 at 5 07 37 PM](https://user-images.githubusercontent.com/6819944/172944689-c1b18208-6f72-406d-8b85-b13cead46724.png)
The idea of the game is to roll two dice and keep track of the unique rolls you make. There are 21 different unique rolls (not counting order) and the goal is to get 8 or more distinct rolls in order to win.

The payouts get quite large, for example, 50 to 1 for getting 15 in a row and 25,000 to 1 for getting 19 in a row.

The textbook discussed two cases - the probability of getting all 21 unique dice rolls without a duplicate (about 1 in 287 million) and the probability of getting a duplicate on your second roll (11 in 216, about 5.1%). Questions that went unanswered were:

- How often the player is likely to get eight or more non-duplicates in a row, that is, how often does the player win?
- What is the expected value (EV) of playing? 

Professional programmer and amateur mathematician that I am, I wrote up some code to simulate the game and then calculated the closed form solutions (using a spreadsheet, of course). Along the way, I made some mistakes, invented some notation, and was stuck for a bit trying to find some patterns, which is probably par for the course for professional mathematicians.

## Target medium

I would like to make some content (probably a video) that walks through this adventure, showing some of the bumps and turns of solving a problem like this. I really liked how Grant walked us through various problem solving processes in his recent [generator function](https://www.youtube.com/watch?v=bOXCLR3Wric) and [cube shadow](https://www.youtube.com/watch?v=ltLUadnCyi0) videos.

I would like to do something in the style of discovering the solution or trying different approaches. I want to inspire and empower junior problem solvers with the confidence to define their own notation and functions to help them tackle problems.

I would like to work with someone who is capable and creative when it comes to presenting objects (like dice) and formulas. 

### More details

I sketched out a write up about how I solved this, but it has collected virtual dust until I saw the SOME2 announcement and decided it would make a good entry.

Here is the outline for that writeup (and I'm happy to share the full document with collaborators).
- Pyramid Dice Game Rules
- Computing the player's probabilities
- Rolling duplicates on the second roll
- Rolling duplicates on the third roll
- Re-evaluating notation
- Rolling duplicates on the fourth roll
- Extending our pattern to 21 rolls
- Verifying our equation and findings
- The Expected Value of Pyramid Dice
- Pyramid Dice Exercises

We certainly do not have to stick with this outline, but the organization made sense to a former version of myself.

[Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1g85LkoChpcAyqMSBnFA0UXgz0JwnMjrBp8TjIfVXbrQ/view) I implemented the calculations in, but they probably aren't the most straightforward at the moment without supplementary explanation. 

The punchline for the calculations are "The players are only likely to win 19.53% of the time and on average will lose over twice as much money (12.37%) compared to a typical casino game", so I can see why this game didn't become very popular in casinos all over the world.

But it would be fun as a side game for a role playing group. 😄 

Keywords: combinatorics, probability, gambling, dice

### Contact details

My email inbox is open. kevin.lubick@gmail.com

**Comment by Sir-Mastermind** [comment]
It could be really neat to animate this with Manim

**Comment by kjlubick** [comment]
I am familiar with the output of Manim (having watched many examples) and with Python (which I think Manim is implemented in?), but have not looked at the API before.

**Comment by kjlubick** [comment]
I learned Manim and put together a video: https://www.youtube.com/watch?v=qa_PsvXrqG4

I'm very pleased with some of the animations, such as:
![Lose2_ManimCE_v0 15 2](https://user-images.githubusercontent.com/6819944/179373672-ccb331f5-c428-4129-9895-4a3884f0d266.gif)
