### ISSUE TITLE
Coder/artist seeking topic idea

### ISSUE THREAD

**Issue by liamappelbe** [leios/SoME_Topics#76]
## Portfolio

I'm a professional software engineer, and I make mathy art in my spare time.
See the Toys > Math section on my site: https://tiusic.com/
A fractal animation music video I made: https://www.youtube.com/watch?v=AaQD-cyXH2A
I have a couple of computer science blog posts here: https://liamappelbe.medium.com/

## Target topic categories

From my CS background I have a good grounding in graph theory and signal processing (FFT etc). But I'm open to any topic that would make a good interactive toy.

## Target medium

I'd like to make an interactive math toy or a blog post that contains interactive components.

### Contact details

liamappelbe@gmail.com

**Comment by PatrickGambill** [comment]
I had a few ideas listed here #10 . If any of these possible projects seem interesting, I would love to collaborate!

**Comment by base6man** [comment]
I have an article about segmenting jumps in [#51](https://github.com/leios/SoME_Topics/issues/51). We could create an interactive program that allows the user to set custom segments for jumps and see how it influences the jumping.

This could even go beyond the scope of my original post, and allow the user to briefly use negative acceleration, or other weird stuff.

**Comment by cmh231** [comment]
Hey! As with everyone else, just want to throw out my current project idea (#57), to see if you're interested. If it sounds like something which might interest you, please do let me know, and we can discuss this in further detail. The one particular point which would be unique to working with you, as opposed to the more general notes I wrote, is that I don't expect my idea would tailor as well to a small game as to a blog post, out of the two media in which you're interested, but I think the latter could still be really fun, and would be very interested in at least discussing the possibility with you.

**Comment by TimeTravelPenguin** [comment]
I am a software engineer, myself, currently doing a double degree in Mathematics and Computer Science.

I would love to see someone make something in regards to the cross-section of the computer science and abstract algebra of functional programming. 

I use Haskell, so the topic of Monads, Monoids, Functors, Applicatives, etc., is super interesting. Especially in regards to how, as a declarative language, they differ from imperative languages such as C/C++ or C# (which is my primary language).

Haskell is increadibly powerful, as an example of a language that encapsulates computation and state with Monads, and I would absolutely love to see someone connect the language (or the paradigms at least) to the concepts and theory from academic literature.

**Comment by liamappelbe** [comment]
Thanks for the suggestions folks. I'll read them and figure out what best suits my skills.

**Comment by RandomCitizen21** [comment]
What about building a physics engine that handles special relativity? MIT made a game that features the world's appearance when traveling at near-light speeds, but it doesn't have anything like object collisions. Maybe we could build something that has the physics of special relativity. 

Since we only have until August, we could start small and find out how much we could add before the deadline.

I've just graduated from college, and I think I know how to build such an engine without running into causality issues (like the twin paradox).

If this is too much to bite off, we can try a different physics concept (like Maxwell's equations, or quantum mechanics, which are easier to simulate than they sound.)

**Comment by liamappelbe** [comment]
Found my project(s), so I'm closing this thread.
