### ISSUE TITLE
Video Game Developer looking to make vector math game

### ISSUE THREAD

**Issue by Quantiset** [leios/SoME_Topics#82]
## About the author

Hello! I'm a student that is passionate about video game development and is currently working on a large-scale video game for the past few years. Though, I'm also looking to join mini side projects like this one comparable to that of game jams :). I don't really have any public finished projects that I can show but feel free to ask to see some private projects that I worked on through discord!

### More details

For this game, I was thinking possibly an introduction to vectors where the player would essentially write a program to manipulate the velocity and acceleration of an object to get it through various levels. This would be similar to games like Human Resource Machine where the player would be able to input code (or potentially code blocks / visual scripting) on the right side with restricted commands that would control the block on the left side of the screen through a goal. For instance, a potential problem would be to move an object in a circle. The player would be able to do this by setting the position.x to sin(TIME) and position.y to cos(TIME). Further questions and ideas are very much appreciated as I am still refining this idea as I go along. Anyone is appreciated -- from experts seeking to morph the programming goal to another field to potential artists!

### Contact details

Discord: Quantiset#8447

### Additional context

I would use Godot for anyone wondering what engine I plan to use!

(Any additional licensing information? If you do not say anything, this post will be considered [CC-BY](https://creativecommons.org/licenses/by/2.0/).)

**Comment by gralnys** [comment]
I could see this being a fun project, given the right parameters. I'd definitely be interested to see where this goes.

**Comment by Quantiset** [comment]
> I could see this being a fun project, given the right parameters. I'd definitely be interested to see where this goes.

Great! Would you be interested in joining it? You can DM on discord to talk further if you'd like!

**Comment by kostis1101** [comment]
Interesting Idea! What kind of tools are you using (e.g. game engine)?

**Comment by Fart-God** [comment]
Hello, I really like this project idea and I'd be interested in helping anyway I can. I don't know too much about development but Godot is something I've been wanting to check out. I would also be interested in helping with any art or music. Additionally I do have some relatively decent video editing skills if you would like to make an accompanying video.

**Comment by Quantiset** [comment]
> Hello, I really like this project idea and I'd be interested in helping anyway I can. I don't know too much about development but Godot is something I've been wanting to check out. I would also be interested in helping with any art or music. Additionally I do have some relatively decent video editing skills if you would like to make an accompanying video.

Great! Feel free to add me on discord if you want to discuss this further! Having someone to create a video to document the process would also be pretty helpful!

**Comment by Yomna-moustafa** [comment]
I like the project idea; I think it would be better if we could expand game idea to be more than introduction to vector and try to discuss more about linear algebra like span, linear transformation in order to make the goal of game is giving the user an experience to visualize the mathematical concept and make it more intuitive
